steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/constantech-website/constantech-website-image', '.']
images:
  - 'gcr.io/constantech-website/constantech-website-image'
options:
  logging: CLOUD_LOGGING_ONLY